#!/bin/bash
input=$(cat)

read -r cwd remaining five_hour seven_day reset_in overhead_pct _session_pct < <(echo "$input" | python3 -c "
import sys,json,time,os
d=json.load(sys.stdin)
ctx=d.get('context_window') or {}
rl=d.get('rate_limits') or {}
fh=rl.get('five_hour') or {}
sd=rl.get('seven_day') or {}
cu=ctx.get('current_usage') or {}
size=ctx.get('context_window_size') or 200000
sid=d.get('session_id') or 'unknown'

def pct(v): return '-' if v is None else '%.0f' % v

cwd=d.get('cwd','') or '-'
remaining=ctx.get('used_percentage')
resets=fh.get('resets_at')
if resets:
    s=max(0,int(resets-time.time()))
    countdown='%dh%02dm' % (s//3600,(s%3600)//60)
else:
    countdown='-'

total=None
if cu:
    total=(cu.get('input_tokens') or 0)+(cu.get('cache_read_input_tokens') or 0)+(cu.get('cache_creation_input_tokens') or 0)

overhead='-'; sess='-'
if total is not None and total>0:
    bdir=os.path.expanduser('~/.claude/cache')
    os.makedirs(bdir,exist_ok=True)
    bf=os.path.join(bdir,'statusline_baseline_global')
    base=None
    try:
        base=int(open(bf).read().strip())
    except: pass
    if base is None or total<base:
        base=total
        try: open(bf,'w').write(str(base))
        except: pass
    overhead='%.0f' % (base*100.0/size)
    sess='%.0f' % (max(0,total-base)*100.0/size)

print(cwd, pct(remaining), pct(fh.get('used_percentage')), pct(sd.get('used_percentage')), countdown, overhead, sess)
" 2>/dev/null)

short_cwd="${cwd/#$HOME/~}"
two_parts=$(echo "$short_cwd" | awk -F/ '{if(NF<=2) print $0; else print $(NF-1)"/"$NF}')

# Session recap (display-only → no keystroke race). Prefer our per-session rolling
# recap (cache/recap_<sid>.txt, regenerated by the session-recap hook, keyed by
# session_id so every pane is independent); fall back to the freshest title record
# in the transcript (custom-title from /rename, else Claude's lazy ai-title).
# Colors: bg hue = md5(title) % 360 (deterministic, shifts as the recap rolls);
# text = the complementary hue (+180). Both high saturation, never neutral.
recap=$(echo "$input" | python3 -c "
import sys,json,os,glob,hashlib,colorsys
d=json.load(sys.stdin)
sid=d.get('session_id') or ''
title=''
cf=os.path.expanduser('~/.claude/cache/recap_%s.txt'%sid) if sid else ''
if cf and os.path.exists(cf):
    try: title=open(cf,encoding='utf-8').read().strip()
    except: pass
if not title:
    tp=d.get('transcript_path')
    if not tp:
        hits=glob.glob(os.path.expanduser('~/.claude/projects/*/%s.jsonl'%sid)) if sid else []
        tp=hits[0] if hits else None
    if tp and os.path.exists(tp):
        try:
            lines=open(tp,encoding='utf-8').read().splitlines()[-600:]
            for ln in reversed(lines):
                try: o=json.loads(ln)
                except: continue
                t=o.get('type')
                if t=='custom-title' and o.get('customTitle'): title=o['customTitle']; break
                if t=='ai-title' and o.get('aiTitle'): title=o['aiTitle']; break
        except: pass
title=' '.join(title.split())
if len(title)>50: title=title[:49]+'…'
def rgb(h,l,s):
    r,g,b=colorsys.hls_to_rgb((h%360)/360.0,l,s)
    return '%d;%d;%d'%(round(r*255),round(g*255),round(b*255))
bg=fg=''
if title:
    hue=int(hashlib.md5(title.encode('utf-8')).hexdigest(),16)%360
    bg=rgb(hue,0.30,0.95)        # vivid, dark-ish backing
    fg=rgb(hue+180,0.72,1.0)     # complementary hue, light, full chroma
sys.stdout.write('%s\x1f%s\x1f%s'%(title,bg,fg))
" 2>/dev/null)
IFS=$'\x1f' read -r title bgc fgc <<<"$recap"

suffix=""
[ -n "$remaining" ] && [ "$remaining" != "-" ] && suffix="${suffix} \033[97mctx:${remaining}%%\033[0m"
[ -n "$overhead_pct" ] && [ "$overhead_pct" != "-" ] && suffix="${suffix} \033[38;5;245m(base:${overhead_pct}%%)\033[0m"
[ -n "$five_hour" ] && [ "$five_hour" != "-" ] && suffix="${suffix} \033[38;5;217m5h:${five_hour}%%\033[0m"
[ -n "$reset_in" ] && [ "$reset_in" != "-" ] && suffix="${suffix} \033[38;5;157m(${reset_in})\033[0m"
[ -n "$seven_day" ] && [ "$seven_day" != "-" ] && suffix="${suffix} \033[36m7d:${seven_day}%%\033[0m"

claude_total=$(pgrep -xc claude 2>/dev/null || echo 0)
others=$((claude_total - 1))
[ "$others" -gt 0 ] && suffix="${suffix} \033[38;5;208malts:${others}\033[0m"

# Line 1: the recap as a hash-colored bar. Line 2: clock + cwd + metrics.
# \033[K erases to end of line using the active bg → fills the whole row, no need
# to know the terminal width (relies on background-color-erase, which tmux honors).
title_line=""
[ -n "$title" ] && title_line="\033[48;2;${bgc};38;2;${fgc}m ${title}\033[K\033[0m\n"

printf "${title_line}\033[38;2;255;181;200m[$(date +%H:%M)]\033[0m \033[38;2;245;237;216m%s\033[0m${suffix}" "$two_parts"
